### ISSUE TITLE
Add "description" field

### ISSUE THREAD

**Issue by jakearchibald** [jakearchibald/background-fetch#11]
Something meaningful to display in the notification, eg the name of the movie/podcast.

**Comment by beverloo** [comment]
To what extent should we enable developers to personalize the notification? We have to be careful to not duplicate too much of the notification API.

I could also imagine adding an icon to represent the download, since many platforms support displaying those. Badges, where supported, could be taken from the Manifest.

**Comment by jakearchibald** [comment]
Also had a request for `icon`.

**Comment by jakearchibald** [comment]
Fixed in https://github.com/jakearchibald/background-fetch/commit/52bf7437807d2b540697d35f7f5002c09543315d
